---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../default

patches:
  - path: patch-resources.yaml
    target:
      group: platform.stackrox.io
      kind: Central
      name: central
      version: v1alpha1
  - path: patch-argocd.yaml
    target:
      group: argoproj.io
      kind: ArgoCD
      name: openshift-gitops
      version: v1alpha1
      #namespace: openshift-gitops
