apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: workload
  annotations:
    argocd.argoproj.io/sync-wave: "10"
    argocd.argoproj.io/compare-options: IgnoreExtraneous
    argocd.argoproj.io/sync-options: Validate=false
  labels:
    gitops.ownedBy: default
spec:
  destination:
    namespace: openshift-gitops
    server: https://kubernetes.default.svc
  project: default
  ignoreDifferences:
    - group: ""
      kind: ServiceAccount
      jsonPointers:
      - /imagePullSecrets
      - /secrets
  source:
    path: gitops/manifests/workload/pipeline/overlays/quarkus
    repoURL: https://github.com/redhat-app-services/gitops-tekton-demo.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: false
      selfHeal: true
