apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJkZW1vLXF1YXktYXBwLnJlZ2lzdHJ5LnN2Yy5jbHVzdGVyLmxvY2FsIjp7InVzZXJuYW1lIjoiYWRtaW4iLCJwYXNzd29yZCI6Im9wZW5zaGlmdCIsImVtYWlsIjoiYWRtaW5AZGVtby5jb20iLCJhdXRoIjoiWVdSdGFXNDZiM0JsYm5Ob2FXWjAifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: quay-registry
  namespace: demo-quarkus-pipeline
type: kubernetes.io/dockerconfigjson
