apiVersion: v1
kind: Secret
metadata:
  name: stackrox-image-puller-token-secret
  annotations:
    kubernetes.io/service-account.name: "stackrox-image-puller" 
type: kubernetes.io/service-account-token
