---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - pipeline-rbac.yaml
  - stackrox-ci-secrets-task.yaml
  - token-secret-pipeline.yaml
  - token-secret-pipelinerun.yaml
