apiVersion: triggers.tekton.dev/v1alpha1
kind: TriggerTemplate
metadata:
  name: build-trigger
  annotations:
    argocd.argoproj.io/sync-wave: "6"
spec:
  resourcetemplates:
  - apiVersion: tekton.dev/v1beta1
    kind: PipelineRun
    metadata:
      name: stackrox-token-secret-pipeline
      namespace: stackrox
    spec:
      params:
        - name: NAMESPACE
          value: demo-quarkus-pipeline
      pipelineRef:
        name: stackrox-token-secret-pipeline
      serviceAccountName: pipeline
      timeout: 1h0m0s
